"""Interpretation engine.

Turns the numeric :class:`AnalysisResults` into plain-English commentary, one
function per memo section, in the register of a credit analyst summarizing a
term sheet. Also produces an illustrative recommendation. Every function
degrades gracefully when a section has not been computed.

Nothing here is investment, credit, or legal advice; the recommendation is a
mechanical illustration of the workflow, never a real credit decision. Pure
Python; no Qt.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from duw.domain.results import AnalysisResults

DISCLAIMER = (
    "This memo is generated by an educational portfolio project. It uses "
    "synthetic and publicly available data, models simplified versions of real "
    "methodologies, and is not affiliated with, endorsed by, or connected to any "
    "bank or financial institution. It does not execute or facilitate trades and "
    "produces no investment, credit, or legal advice. The recommendation below is "
    "illustrative only and must not be used for any real underwriting, trading, or "
    "credit decision."
)

# Grades at or below this are treated as sub-investment-grade for the heuristic.
_SUBINVESTMENT = {"BB", "B", "CCC", "CC", "C", "D"}
_DISTRESSED = {"CCC", "CC", "C", "D"}


@dataclass(frozen=True)
class Recommendation:
    """An illustrative underwriting verdict and its rationale."""

    verdict: str
    rationale: str


def _fmt(x: float | None) -> str:
    return "n/a" if x is None or math.isnan(x) else f"{x:,.0f}"


def interpret_counterparty(results: AnalysisResults) -> str:
    """Commentary on the counterparty's creditworthiness."""
    profile = results.credit_profile
    cp = results.counterparty
    if profile is None:
        return "No counterparty credit assessment is available."
    name = cp.name if cp is not None else profile.counterparty_id
    parts = [f"{name} is assessed at internal grade {profile.internal_grade}."]
    if profile.altman_zone is not None and profile.altman_z is not None:
        parts.append(
            f"Its Altman Z-score of {profile.altman_z:.2f} places it in the "
            f"{profile.altman_zone} zone."
        )
    if profile.merton_pd is not None:
        dtd = (
            f" (distance-to-default {profile.distance_to_default:.2f})"
            if profile.distance_to_default is not None
            and math.isfinite(profile.distance_to_default)
            else ""
        )
        parts.append(
            f"The Merton one-year default probability is {profile.merton_pd:.2%}{dtd}."
        )
    if profile.pd_term_structure:
        last_t, last_pd = profile.pd_term_structure[-1]
        parts.append(
            f"Cumulative default probability reaches {last_pd:.1%} by {last_t:.0f}y."
        )
    return " ".join(parts)


def interpret_exposure(results: AnalysisResults) -> str:
    """Commentary on the exposure profile."""
    exp = results.exposure
    if exp is None or not exp.time_grid:
        return "No exposure profile is available."
    return (
        f"Expected positive exposure (EPE) is {_fmt(exp.epe)}, and potential "
        f"future exposure peaks at {_fmt(exp.peak_pfe)} (95%) around "
        f"{exp.peak_pfe_time:.1f}y before amortizing toward maturity. Exposure "
        "builds as the risk factors diffuse, then decays as the trade rolls down."
    )


def interpret_collateral(results: AnalysisResults) -> str:
    """Commentary on the collateral (CSA) mitigation."""
    col = results.collateral
    if col is None or not col.time_grid:
        return "No collateral analysis is available."
    unc = col.peak_pfe_uncollateralized
    coll = col.peak_pfe_collateralized
    if not math.isnan(unc) and unc > 0 and not math.isnan(coll):
        reduction = 1.0 - coll / unc
        return (
            f"Under the modelled CSA (threshold {_fmt(col.threshold)}, initial "
            f"margin {_fmt(col.initial_margin)}, {col.mpor_days}-day MPoR), peak "
            f"PFE falls from {_fmt(unc)} to {_fmt(coll)}, a {reduction:.0%} "
            "reduction. Residual exposure reflects the margin period of risk."
        )
    return "Collateral has a negligible effect on the modelled exposure."


def interpret_cva(results: AnalysisResults) -> str:
    """Commentary on the CVA / DVA / BCVA."""
    cva = results.cva
    if cva is None or math.isnan(cva.cva):
        return "No CVA analysis is available."
    return (
        f"The credit valuation adjustment (CVA) is {_fmt(cva.cva)}, the own-credit "
        f"debit adjustment (DVA) is {_fmt(cva.dva)}, and the bilateral net (BCVA) "
        f"is {_fmt(cva.bcva)}. CVA is the market price of the counterparty's "
        "default risk over the life of the netting set."
    )


def interpret_limits(results: AnalysisResults) -> str:
    """Commentary on the limit check."""
    lim = results.limits
    if lim is None or math.isnan(lim.utilization):
        return "No limit check is available."
    state = "breaches" if lim.breach else "sits within"
    incremental = _fmt(lim.incremental_peak_pfe)
    return (
        f"Against a limit of {_fmt(lim.limit)}, the proposed trade {state} the "
        f"line at {lim.utilization:.0%} utilization. It adds {incremental} of "
        f"incremental peak PFE, leaving {_fmt(lim.headroom)} of headroom."
    )


def recommend(results: AnalysisResults) -> Recommendation:
    """Produce an illustrative verdict from the results (not credit advice)."""
    limits = results.limits
    profile = results.credit_profile
    grade = profile.internal_grade if profile is not None else None
    zone = profile.altman_zone if profile is not None else None
    util = limits.utilization if limits is not None else math.nan

    reasons: list[str] = []
    verdict = "Approve"

    if limits is not None and limits.breach:
        verdict = "Decline"
        reasons.append(
            f"the trade breaches the counterparty limit ({util:.0%} utilization)"
        )
    if grade in _DISTRESSED or zone == "distress":
        verdict = "Decline"
        reasons.append(
            f"the counterparty is distressed (grade {grade}, Altman zone {zone})"
        )
    elif grade in _SUBINVESTMENT and verdict == "Approve":
        verdict = "Approve with conditions"
        reasons.append(f"the counterparty is sub-investment grade ({grade})")

    if (
        verdict == "Approve"
        and limits is not None
        and not math.isnan(util)
        and util > 0.80
    ):
        verdict = "Approve with conditions"
        reasons.append(f"limit headroom is tight ({util:.0%} utilization)")

    if verdict == "Approve":
        reasons.append(
            "exposure sits comfortably within limit and the counterparty is "
            "investment grade"
        )

    rationale = "; ".join(reasons)
    rationale = rationale[:1].upper() + rationale[1:] + "."
    return Recommendation(verdict=verdict, rationale=rationale)


def section_commentary(results: AnalysisResults) -> dict[str, str]:
    """All section commentary, keyed by section name."""
    return {
        "counterparty": interpret_counterparty(results),
        "exposure": interpret_exposure(results),
        "collateral": interpret_collateral(results),
        "cva": interpret_cva(results),
        "limits": interpret_limits(results),
    }
